windows_container:
  image: cirrusci/windowsservercore:2019

env:
  DAGGER_VERSION: 0.2.5
  CIRRUS_SHELL: powershell

docker_builder:
  platform: windows
  os_version: '2019'
  # Start of _script steps
  echo_docker_debug_info_script: |
    docker version
    docker info
  install_scoop_base_scoop_then_dagger_then_dagger_do_script: |
    Invoke-WebRequest -UseBasicParsing 'get.scoop.sh' -OutFile 'Install-Scoop.ps1'
    .\Install-Scoop.ps1 -RunAsAdmin
    scoop which scoop
    scoop install 7zip git
    scoop config SCOOP_REPO 'https://github.com/Ash258/Scoop-Core'
    scoop update
    scoop status
    scoop update '*'
    scoop status
    scoop checkup
    scoop install dagger@${env:DAGGER_VERSION}
    scoop which dagger
    ~\scoop\apps\dagger\current\dagger.exe version
    ~\scoop\apps\dagger\current\dagger.exe project init
    ~\scoop\apps\dagger\current\dagger.exe project update
    ~\scoop\apps\dagger\current\dagger.exe do lint
