windows_container:
  image: cirrusci/windowsservercore:2019

env:
  DAGGER_VERSION: 0.2.5
  CIRRUS_SHELL: powershell

task:
  debug_try_stop_host_network_service: |
    Stop-Service hns
    del C:\ProgramData\Microsoft\Windows\HNS\HNS.dat
    Start-Service hns
  download_docker_daemon_script: |
    (New-Object System.Net.WebClient).DownloadFile('https://download.docker.com/win/static/stable/x86_64/docker-20.10.14.zip','docker.zip')
    Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles
  register_and_start_docker_daemon_script: |
    &$Env:ProgramFiles\Docker\dockerd --register-service
    Start-Service docker
  echo_docker_debug_info_script: |
    docker version
    docker info
  install_scoop_base_scoop_script: |
    Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
    scoop which scoop
    scoop install 7zip git
    scoop config SCOOP_REPO 'https://github.com/Ash258/Scoop-Core'
    scoop update
    scoop status
    scoop checkup
  scoop_install_dagger_script: |
    scoop install dagger@${env:DAGGER_VERSION}
  dagger_do_lint_script: |
    dagger do lint
